# Generated by Django 4.1 on 2025-07-30 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_account_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User name', max_length=50, unique=True, verbose_name='Name')),
                ('scientific_name', models.CharField(help_text='User name', max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
                'db_table': 'tree',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlantedTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Age of Tree', unique=True, verbose_name='Age')),
                ('planted_at', models.DateTimeField(help_text='When it was planted', verbose_name='Planted At')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude that was planted', max_digits=9, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude  that was planted', max_digits=9, verbose_name='Latitude ')),
                ('account', models.ForeignKey(help_text='Planted Tree', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planted_tree', to='accounts.account', verbose_name='Planted Tree')),
                ('tree', models.ForeignKey(help_text='Planted Tree', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planted_tree', to='trees.tree', verbose_name='Planted Tree')),
                ('user', models.ForeignKey(help_text='Planted Tree', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planted_tree', to=settings.AUTH_USER_MODEL, verbose_name='Planted Tree')),
            ],
            options={
                'verbose_name': 'Planted Tree',
                'verbose_name_plural': 'Planted Trees',
                'db_table': 'planted_tree',
                'ordering': ['id'],
            },
        ),
    ]
