# Generated by Django 4.1 on 2025-07-29 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User name', max_length=50, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date of the account', verbose_name='Creation date')),
                ('active', models.BooleanField(default=True, help_text='', verbose_name='Active Account ')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(help_text='Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='accounts.account', verbose_name='Account')),
                ('user', models.ForeignKey(help_text='User', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User of Account',
                'verbose_name_plural': 'Users of Accounts',
                'db_table': 'account_user',
                'ordering': ['id'],
            },
        ),
    ]
