# Generated by Django 4.1 on 2025-07-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, help_text='', verbose_name='Active Account '),
        ),
    ]
